# Review artefacts for one assembled cut, in its --out directory: timing.md, captions.srt (also copied next to the video
# as <video>.srt), contact-sheet.png, thumbnail.png (and, with --frames, one frame per second in <out>/frames/).
#
#   ruby demo/video/finish.rb --out out/portfolio [--frames]
require "json"
require "fileutils"
require "optparse"
require "open3"

HERE = __dir__
opts = { out: File.join(HERE, "out/portfolio"), frames: false }
OptionParser.new do |o|
  o.on("--out DIR") { opts[:out] = File.expand_path(_1) }
  o.on("--frames") { opts[:frames] = true }
end.parse!

def run(*cmd)
  out, status = Open3.capture2e(*cmd)
  abort "failed: #{cmd.join(' ')}\n#{out.lines.last(15).join}" unless status.success?
  out
end

tl = JSON.parse(File.read(File.join(opts[:out], "timeline.json"), encoding: "UTF-8"))
video = File.join(opts[:out], tl["video"])
beats = tl["beats"]

def mmss(t) = format("%d:%05.2f", (t / 60).floor, t % 60)

# timing.md
rows = beats.map do |b|
  "| #{b['id']} | #{b['segment']} | #{mmss(b['start'])} | #{mmss(b['end'])} | #{(b['end'] - b['start']).round(1)} s | #{b['visual']} | #{b['text'].gsub('|', '/')} |"
end
File.write(File.join(opts[:out], "timing.md"), <<~MD)
  # Scene and timing index

  `#{File.basename(tl['video'])}` (#{tl['cut']} cut), #{tl['duration'].round(1)} s, 1920x1080. Generated by bin/demo; times are on the final video's timeline.

  | Beat | Segment | Start | End | Length | Visual | Narration |
  |---|---|---|---|---|---|---|
  #{rows.join("\n")}
MD

# captions.srt: each beat's narration split into sentence cues, timed in proportion to their length
def srt_time(t)
  ms = (t * 1000).round
  format("%02d:%02d:%02d,%03d", ms / 3_600_000, ms / 60_000 % 60, ms / 1000 % 60, ms % 1000)
end

def wrap(text, width = 44)
  lines = [ "" ]
  text.split.each { |w| (lines.last.empty? ? lines.last << w : (lines.last.size + 1 + w.size <= width ? lines.last << " " << w : lines << w.dup)) }
  lines.join("\n")
end
cues = []
beats.each do |b|
  sentences = b["text"].split(/(?<=[.!?:])\s+/)
  total = sentences.sum(&:size).to_f
  t = b["narration_start"]
  span = b["narration_end"] - b["narration_start"]
  sentences.each do |s|
    d = span * s.size / total
    cues << [ t, t + d, s ]
    t += d
  end
end
srt = cues.each_with_index.map { |(a, z, s), i| "#{i + 1}\n#{srt_time(a)} --> #{srt_time(z)}\n#{wrap(s)}\n" }.join("\n")
File.write(File.join(opts[:out], "captions.srt"), srt)
File.write(video.sub(/\.mp4\z/, ".srt"), srt)

# contact-sheet.png: one labelled frame per beat (this ffmpeg build has no drawtext, so the labels are drawn in a page)
run("node", File.join(HERE, "contact-sheet.mjs"), "--out", opts[:out])

# thumbnail.png: the title card, after the fade-in
run("ffmpeg", "-y", "-v", "error", "-ss", "1.5", "-i", video, "-frames:v", "1", File.join(opts[:out], "thumbnail.png"))

if opts[:frames]
  fdir = File.join(opts[:out], "frames")
  FileUtils.rm_rf(fdir)
  FileUtils.mkdir_p(fdir)
  run("ffmpeg", "-y", "-v", "error", "-i", video, "-vf", "fps=1", File.join(fdir, "f%03d.png"))
end
puts "timing.md, captions.srt (#{cues.size} cues), contact-sheet.png, thumbnail.png"
